
[[pages]]
name = "Data Management"
icon = "ğŸ¤¹â€â™‚ï¸"
is_section = true

[[pages]]
path = "dataloader.py"
name = "Data Load"
icon = "ğŸ“Š"

[[pages]]
path = "page2.py"
name = "Page 2"
icon = "ğŸˆ"


# [[pages]]
# path = "example_four.py"
# name = "Try hiding pages"
# icon = "ğŸ“–"

# [[pages]]
# name = "Other apps"
# icon = ":horse:"
# is_section = true

# [[pages]]
# path = "example_three.py"

# [[pages]]
# path = "example_five.py"
# name = "Example Five"
# icon = "ğŸ§°"
# url_path = "a_very_long_page_title"
