
[[pages]]
name = "Portfolio Metadata"
icon = "ğŸ“Š"
is_section = true

[[pages]]
path = "dataloader.py"
name = "Data Loading"
icon = "âš¡"

[[pages]]
name = "Chance of Development"
icon = "ğŸ²"
is_section = true

[[pages]]
path = "page2.py"
name = "Page 2"
icon = "ğŸˆ"

# [[pages]]
# path = "example_five.py"
# name = "Example Five"
# icon = "ğŸ§°"
# url_path = "a_very_long_page_title"
