
[[pages]]
name = "Portfolio Metadata"
icon = "ğŸ’¼"
is_section = true

[[pages]]
path = "dataloader.py"
name = "Data Loading"
icon = "âš¡"

[[pages]]
path = "essbase_data_preparation.py"
name = "Data Prep"
icon = "ğŸ"


[[pages]]
name = "Chance of Development"
icon = "ğŸ²"
is_section = true

[[pages]]
path = "dataloader_dev_chance.py"
name = "Data Loading"
icon = "âš¡"

[[pages]]
path = "dev_chance_visuals.py"
name = "Visualisation"
icon = "ğŸ“Š"

